name: "Development - Destroy"

defaults:
  run:
    working-directory: environments/development

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Destroy"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_LOG: ${{ secrets.TF_LOG }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
