name: "Development - Plan"

defaults:
  run:
    working-directory: environments/development

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Plan"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_LOG: ${{ secrets.TF_LOG }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: Validate
        run: terraform validate
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
